[package]
name = "pepr"
version = "0.1.0"
authors = ["Lorenz Leutgeb <lorenz@mpi-inf.mpg.de>"]
edition = "2021"

[dependencies]
cfg-if = "0.1.2"
pest = "2.1.3"
pest_derive = "2.1.0"
clap = { version = "3.1.1", features = ["derive"] }
string-interner = "0.14.0"
itertools = "0.10.3"
minilp = "0.2.2"
